# Generated by Django 4.2.7 on 2026-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
