# Generated by Django 4.2.7 on 2026-03-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('classroom', 'first_name', 'last_name')},
        ),
    ]
