# Generated by Django 4.2.7 on 2026-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant')], default='student', max_length=10),
        ),
    ]
