# Generated by Django 4.2.7 on 2026-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_role_pendinguser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
