# Generated by Django 4.2.7 on 2025-10-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_domain', models.CharField(default='Mathématiques', max_length=100)),
                ('user_level', models.CharField(default='Collège (6ᵉ – 3ᵉ)', max_length=100)),
                ('user_exercise_type', models.CharField(default='Problème à résoudre', max_length=100)),
                ('user_expectation', models.CharField(default='Solution étape par étape', max_length=100)),
                ('user_info', models.TextField(blank=True, default='')),
                ('detected_branch', models.CharField(default='Général', max_length=50)),
                ('detected_branch_explanation', models.TextField(blank=True)),
                ('domain_mismatch', models.TextField(blank=True, null=True)),
                ('response_datetime', models.CharField(max_length=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('solution', models.JSONField(blank=True, null=True)),
                ('content_type', models.CharField(default='GENERAL', max_length=50)),
                ('educational_mode', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de correction',
                'verbose_name_plural': 'Historiques de correction',
                'ordering': ['-created_at'],
            },
        ),
    ]
