# Generated by Django 4.2.7 on 2025-11-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_chatsession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='gemini_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
