# Generated by Django 4.2.7 on 2025-11-04 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0003_chatmessage_gemini_response_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='corrections/%Y/%m/%d/')),
                ('domaine', models.CharField(default='Mathématiques', max_length=100)),
                ('niveau', models.CharField(default='Collège', max_length=100)),
                ('type_exercice', models.CharField(default='Problème', max_length=100)),
                ('attente', models.CharField(default='Étape par étape', max_length=100)),
                ('infos_complementaires', models.TextField(blank=True)),
                ('correction_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Photo',
                'verbose_name_plural': 'Corrections Photo',
                'ordering': ['-created_at'],
            },
        ),
    ]
