# Generated by Django 4.2.7 on 2025-11-12 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_imagecorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Corrige Moi', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('support_email', models.EmailField(default='support@corrigemoi.ci', max_length=254)),
                ('support_whatsapp', models.CharField(default='+2250707070707', max_length=20)),
                ('support_phone', models.CharField(blank=True, default='', max_length=20)),
                ('support_facebook', models.URLField(blank=True, default='')),
                ('support_instagram', models.URLField(blank=True, default='')),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('default_language', models.CharField(default='fr', max_length=10)),
                ('primary_color', models.CharField(default='#02A195', max_length=7)),
                ('master_api_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.DeleteModel(
            name='ExerciseProcessing',
        ),
    ]
