# Generated by Django 4.2.7 on 2026-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='app_store_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien App Store'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='play_store_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien Play Store'),
        ),
    ]
