# Generated by Django 4.2.7 on 2026-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_sitesettings_store_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corrections/%Y/%m/%d/'),
        ),
    ]
