# Generated by Django 4.2.7 on 2026-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_add_image_to_correctionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Clé API Gemini'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='geniuspay_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Clé API GeniusPay'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='geniuspay_api_secret',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Secret API GeniusPay'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='geniuspay_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Secret Webhook GeniusPay'),
        ),
    ]
