# Generated by Django 4.2.7 on 2025-10-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_best_plan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image_corrections_limit', models.PositiveIntegerField(default=0, help_text="Nombre d'envois d'images autorisés (0 = illimité)")),
                ('chat_questions_limit', models.PositiveIntegerField(default=0, help_text='Nombre de questions au chatbot autorisées (0 = illimité)')),
                ('duration', models.PositiveIntegerField(choices=[(0, 'Illimité'), (30, '30 jours'), (90, '90 jours'), (365, '1 an')], default=30, help_text='Durée en jours (0 = illimité)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pack Abonnement',
                'verbose_name_plural': 'Packs Abonnement',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_key', models.CharField(default=subscriptions.models.generate_api_key, max_length=100, unique=True)),
                ('image_corrections_remaining', models.PositiveIntegerField(default=0)),
                ('chat_questions_remaining', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pack')},
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMAGE_CORRECTION', "Correction d'image"), ('CHAT_QUESTION', 'Question au chatbot')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='subscriptio_timesta_93b94c_idx')],
            },
        ),
    ]
