# Generated by Django 4.2.7 on 2026-02-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Souscription'), ('upgrade', 'Upgrade'), ('renewal', 'Renouvellement')], max_length=20),
        ),
    ]
