# Generated by Django 4.2.7 on 2026-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_seed_default_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Pack gratuit (sans paiement)'),
        ),
    ]
