


"""
Django settings for backend_project project.
Generated by 'django-admin startproject' using Django 3.2.25.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta  # Pour JWT

load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Augmenter timeout serveur
os.environ['DJANGO_SERVER_TIMEOUT'] = '60'

# Clé API Gemini
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# GeniusPay Payment API
GENIUSPAY_BASE_URL       = 'https://pay.genius.ci/api/v1/merchant'
GENIUSPAY_API_KEY        = os.getenv('GENIUSPAY_API_KEY', '')
GENIUSPAY_API_SECRET     = os.getenv('GENIUSPAY_API_SECRET', '')
GENIUSPAY_WEBHOOK_SECRET = os.getenv('GENIUSPAY_WEBHOOK_SECRET', '')

# Mode mock : simule la page de paiement en local (mettre False en production)
PAYMENT_MOCK_MODE = False

# SECURITY: chargée depuis .env — ne jamais hardcoder en production
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-only-key-change-in-production'
)

# SECURITY: False en production (variable d'env DEBUG=True uniquement en dev)
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ✅ CORS : Autoriser origines spécifiques
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '10.245.228.225',
    '172.20.10.2',
    '10.245.68.224' , 
    '10.245.8.223',
    '172.20.10.2',
    '10.245.8.222',
    '.onrender.com',
    '10.244.164.222',
    '192.168.1.49',
    '192.168.1.30',
    '10.244.164.222',
    '192.168.1.8',
    '192.168.1.19',
]


# ✅ Autoriser headers et méthodes
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",  # ✅ Nécessaire pour JWT
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ✅ Autoriser credentials (JWT tokens)
CORS_ALLOW_CREDENTIALS = True

# ✅ REST Framework avec JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT
        'rest_framework.authentication.SessionAuthentication',       # Session (admin)
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Exige authentification
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'signup': '5/min',
        'otp': '5/min',
        'login': '10/min',
        'password_reset': '5/min',
    },
}

# ✅ Configuration SimpleJWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # 30 min en production
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # 7 jours
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'AUTH_HEADER_TYPES': ('Bearer',),  # Format "Bearer <token>"
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'authentification',
    'treatment',
    'subscriptions',
    'corsheaders',
    'custom_admin',
    'classes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ Doit être en PREMIER
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

whatsapp='+2'


WSGI_APPLICATION = 'backend_project.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')






# Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Encoding
DEFAULT_CHARSET = 'utf-8'
DEFAULT_CONTENT_TYPE = 'application/json; charset=utf-8'

# Custom user model
AUTH_USER_MODEL = 'authentification.CustomUser'

# Redirection pour @login_required → page de connexion du dashboard custom
LOGIN_URL = '/custom-admin/login/'








# 0151655248
# Dadi2003







