


"""
Django settings for backend_project project.
Generated by 'django-admin startproject' using Django 3.2.25.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta  # Pour JWT

load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Augmenter timeout serveur
os.environ['DJANGO_SERVER_TIMEOUT'] = '60'

# Clé API Gemini
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)*_3xsh-gg-kg@eca5y(tbiib&bd6qi3sux=s&58$^s-9!9bv_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ✅ CORS : Autoriser origines spécifiques
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '10.245.228.225',
    '172.20.10.2',
    '10.245.68.224' , 
    '10.245.8.223',
    '172.20.10.2',
    '10.245.8.222',
    '.onrender.com'
    
]


# ✅ Autoriser headers et méthodes
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",  # ✅ Nécessaire pour JWT
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ✅ Autoriser credentials (JWT tokens)
CORS_ALLOW_CREDENTIALS = True

# ✅ REST Framework avec JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT
        'rest_framework.authentication.SessionAuthentication',       # Session (admin)
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Exige authentification
    ],
}

# ✅ Configuration SimpleJWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Durée token accès
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Durée refresh
    'ROTATE_REFRESH_TOKENS': False, 
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'AUTH_HEADER_TYPES': ('Bearer',),  # Format "Bearer <token>"
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'authentification',
    'treatment',
    'subscriptions',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ Doit être en PREMIER
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_project.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')





# Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Encoding
DEFAULT_CHARSET = 'utf-8'
DEFAULT_CONTENT_TYPE = 'application/json; charset=utf-8'

# Custom user model
AUTH_USER_MODEL = 'authentification.CustomUser'








# from pathlib import Path
# from dotenv import load_dotenv
# import os

# load_dotenv()

# BASE_DIR = Path(__file__).resolve().parent.parent

# # === PRODUCTION ===
# DEBUG = False
# SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-secret-key')
# ALLOWED_HOSTS = ['*']

# # === GEMINI ===
# GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# # === DATABASE (Railway auto) ===
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.parse(os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'))
# }

# # === STATIC FILES ===
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # === CORS ===
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True

# # === REST + JWT ===
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
# }

# # === APPS ===
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'rest_framework_simplejwt',
#     'corsheaders',
#     'authentification',
#     'treatment',
#     'subscriptions',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
# ]

# ROOT_URLCONF = 'backend_project.urls'
# WSGI_APPLICATION = 'backend_project.wsgi.application'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# AUTH_USER_MODEL = 'authentification.CustomUser'

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'








