name: Deploy to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/CORRECTION-APP-BACKEND
            git pull origin prod
            source venv/bin/activate
            pip install -r requirements.txt --quiet
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart corrigemoi
            echo "Déployé avec succès !"
